version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prstats
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./driver:/app/driver

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
